### ISSUE TITLE
Use relative addresses in KNN model and training scripts

### ISSUE THREAD

**Issue by martian0x80** [Char-Coders/vihaan_6.O#3]
Replace absolute addresses with relative addresses (path) in `knn_model.py`, `train.py` and upload the `.xml` file in the same directory as the model. 
@Shiv-Expert2503

**Comment by LakshayGMZ** [comment]
> Replace absolute addresses with relative addresses (path) in `knn_model.py`, `train.py` and upload the `.xml` file in the same directory as the model. @Shiv-Expert2503

lmao dead @martian0x80
